# Generated by Django 4.0.4 on 2022-05-23 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='provider',
        ),
        migrations.AddField(
            model_name='service',
            name='providers',
            field=models.ManyToManyField(to='account.record'),
        ),
    ]
